# Generated by Django 5.2.5 on 2025-09-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_system_app', '0002_quiz_user_role_question_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_maker', to='quiz_system_app.user'),
        ),
    ]
